# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Kylin5 CI

on:
  push:
    branches: [ "pre-kylin5" ]
  pull_request:
    branches: [ "pre-kylin5" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'oracle'
          cache: maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

  test:
    runs-on: ubuntu-22.04
    needs: build
    strategy:
      fail-fast: false
      matrix:
        group: [
          { name: 'UT-Group1', modules: 'src/core-common,src/query,src/query-common,src/core-storage,src/core-job' },
          { name: 'UT-Group2', modules: 'src/kylin-it' }
        ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Set up JDK 8
        uses: actions/setup-java@v5
        with:
          java-version: '8'
          distribution: 'oracle'
          cache: maven
      - name: Run tests ${{ matrix.group.name }}
        run: mvn clean test --fail-at-end -DargLine='-Xms4G -Xmx8G' -DfailIfNoTests=false -Duser.timezone=GMT+8 -pl ${{ matrix.group.modules }} -am
